### ISSUE TITLE
When creating a team...nothing happens. And says 0 remaining spots available. 

### ISSUE THREAD

**Issue by riyazhdholakia** [AgaKhanFoundation/WCF-iOS#247]
Just created a team and I have 0 spots remaining on team
![Image from iOS (1)](https://user-images.githubusercontent.com/33207542/65781351-7b440c80-e119-11e9-973d-f155b045e378.png)

**Comment by jayson528** [comment]
hey, do you mind if i have ago at fixing this issue?

**Comment by samisuteria** [comment]
More than welcome to :)

**Comment by jayson528** [comment]
> More than welcome to :)

hey, i was wondering if you possibly had a facebook account that i could use for testing on this app? I don't use facebook my self, i made an account just for this reason and i'm unable to login successfully, and i need to be logged in in order to create a team and such. please let me know if you have any suggestions.

<img width="584" alt="Screen Shot 2019-10-08 at 1 25 35 PM" src="https://user-images.githubusercontent.com/42183771/66418126-6bf17880-e9cf-11e9-8ddf-cbe4b1ad5815.png">
